services:
  test:
    image: maven:3.9.11-eclipse-temurin-21

    working_dir: /src

    volumes:
      - type: bind
        source: .
        target: /src

    entrypoint: ["mvn", "-Ptest", "clean", "verify", "--no-transfer-progress"]

    container_name: test

    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SHOW_SQL=false
      - SERVER_PORT=8080

    restart: no

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s