name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run tests with docker-compose
        env:
          RSA_PUBLIC_KEY: ${{ secrets.RSA_PUBLIC_KEY }}
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
        run: docker compose -f docker-compose-test.yml up --quiet-pull --abort-on-container-exit --exit-code-from test

      - name: Clean up
        if: always()
        run: docker compose -f docker-compose-test.yml down -v